USB: isp116x: isa_rom_*() calls should depend on CONFIG_ATARI_ROM_ISA
If CONFIG_ATARI_ROM_ISA=n:

drivers/usb/host/isp116x.h: In function ‘isp116x_write_addr’:
drivers/usb/host/isp116x.h:382: error: implicit declaration of function ‘isa_rom_writew_raw’
drivers/usb/host/isp116x.h: In function ‘isp116x_raw_write_data16’:
drivers/usb/host/isp116x.h:394: error: implicit declaration of function ‘isa_rom_writew’
drivers/usb/host/isp116x.h: In function ‘isp116x_read_data16’:
drivers/usb/host/isp116x.h:402: error: implicit declaration of function ‘isa_rom_readw_raw’
drivers/usb/host/isp116x.h: In function ‘isp116x_raw_read_data16’:
drivers/usb/host/isp116x.h:411: error: implicit declaration of function ‘isa_rom_readw’

The isa_rom_*() calls should depend on CONFIG_ATARI_ROM_ISA instead of
on CONFIG_ATARI.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Michael Schmitz <schmitzmic@gmail.com>