CONFIG_SWAP=n: include/linux/swap.h needs <linux/pagemap.h>
When compiling a m68k kernel with CONFIG_SWAP=n, I get:

    include/asm-generic/tlb.h: In function 'tlb_flush_mmu':
    include/asm-generic/tlb.h:76: error: implicit declaration of function 'release_pages'
    include/asm-generic/tlb.h: In function 'tlb_remove_page':
    include/asm-generic/tlb.h:105: error: implicit declaration of function 'page_cache_release'

because include/linux/swap.h defines free_page_and_swap_cache() and
free_pages_and_swap_cache() to page_cache_release() resp. release_pages()
without including <linux/pagemap.h>.

As the comment in include/linux/swap.h says it cannot include <linux/pagemap.h>
on sparc