m68k: Make sure {read,write}s[bwl]() are always defined
If CONFIG_ATARI_ROM_ISA is defined (e.g. allmodconfig), musb fails to
compile with:

In file included from drivers/usb/musb/musb_core.h:68,
                 from drivers/usb/musb/musb_core.c:104:
drivers/usb/musb/musb_io.h:45: error: conflicting types for ‘raw_insl’
arch/m68k/include/asm/raw_io.h:200: error: previous definition of ‘raw_insl’ was here
drivers/usb/musb/musb_io.h:47: error: conflicting types for ‘raw_insw’
arch/m68k/include/asm/raw_io.h:121: error: previous definition of ‘raw_insw’ was here
drivers/usb/musb/musb_io.h:52: error: conflicting types for ‘raw_outsl’
arch/m68k/include/asm/raw_io.h:240: error: previous definition of ‘raw_outsl’ was here
drivers/usb/musb/musb_io.h:54: error: conflicting types for ‘raw_outsw’
arch/m68k/include/asm/raw_io.h:161: error: previous definition of ‘raw_outsw’ was here
make[4]: *** [drivers/usb/musb/musb_core.o] Error 1

This happens because musb_io.h provides default implementations for
{read,write}s[bwl]() on most platforms, some of which conflict with their
Atari ROM ISA counterparts.

To avoid adding a check for CONFIG_ATARI_ROM_ISA to musb_io.h, make sure
{read,write}s[bwl]() are always defined on m68k, and disable the default
implementations in musb_io.h on m68k, like is already done for several
other architectures.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Felipe Balbi <balbi@ti.com>