bitops: Move find_next_bit.o from lib-y to obj-y
If there are no builtin users of find_next_bit_le() and
find_next_zero_bit_le(), these functions are not present in the kernel
image, causing m68k allmodconfig to fail with:

ERROR: "find_next_zero_bit_le" [fs/ufs/ufs.ko] undefined!
ERROR: "find_next_bit_le" [fs/udf/udf.ko] undefined!
ERROR: "find_next_zero_bit_le" [fs/reiserfs/reiserfs.ko] undefined!
ERROR: "find_next_bit_le" [fs/ocfs2/ocfs2.ko] undefined!
ERROR: "find_next_zero_bit_le" [fs/ocfs2/ocfs2.ko] undefined!
ERROR: "find_next_zero_bit_le" [fs/nilfs2/nilfs2.ko] undefined!
ERROR: "find_next_bit_le" [fs/ext4/ext4.ko] undefined!
ERROR: "find_next_zero_bit_le" [fs/ext4/ext4.ko] undefined!
ERROR: "find_next_zero_bit_le" [fs/ext3/ext3.ko] undefined!
ERROR: "find_next_zero_bit_le" [fs/ext2/ext2.ko] undefined!
ERROR: "find_next_zero_bit_le" [drivers/media/rc/ite-cir.ko] undefined!
ERROR: "find_next_bit_le" [drivers/media/rc/ite-cir.ko] undefined!
ERROR: "find_next_zero_bit_le" [drivers/md/dm-log.ko] undefined!
ERROR: "find_next_bit_le" [drivers/block/drbd/drbd.ko] undefined!
ERROR: "find_next_zero_bit_le" [drivers/block/drbd/drbd.ko] undefined!

This started to happen after commit 171d809df1896c1022f9778cd2788be6c255a7dc
("m68k: merge mmu and non-mmu bitops.h"), as m68k had its own inline
versions before.

commit 63e424c84429903c92a0f1e9654c31ccaf6694d0 ("arch: remove
CONFIG_GENERIC_FIND_{NEXT_BIT,BIT_LE,LAST_BIT}") added find_last_bit.o to
obj-y (so it's always included), but find_next_bit.o to lib-y (so it gets
removed by the linker if there are no builtin users).

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Greg Ungerer <gerg@uclinux.org>