m68k/head.S: CONSOLE_DEBUG should depend on CONFIG_FONT_SUPPORT
allmodconfig:

arch/m68k/kernel/head.o: In function `debug_cons_nputs':
(.init.text+0x1500): undefined reference to `font_vga_8x8'
make[3]: *** [vmlinux] Error 1

CONFIG_FONT_8x8=y, but CONFIG_FRAMEBUFFER_CONSOLE=m and
CONFIG_FONT_SUPPORT=m, causing the font to be modular.

Introduced by commit 0ff3cc858e74436c2234183ea2dd200474cba09a ("m68k:
Multi-platform EARLY_PRINTK"), which dropped a dependency on
CONFIG_FRAMEBUFFER_CONSOLE (FRAMEBUFFER_CONSOLE selects FONT_SUPPORT).

Make CONSOLE_DEBUG depend on CONFIG_FONT_SUPPORT to fix this.

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>